#!/bin/bash

echo "🔧 VS Code Extension Issues Fix Script"
echo "======================================"
echo ""

echo "📋 Issues to fix:"
echo "1. GitHub Copilot Chat 'Unknown tool' errors"
echo "2. GitHub Pull Request extension issues"
echo ""

echo "🛠️  Steps to fix VS Code issues:"
echo ""
echo "1️⃣  Reload VS Code:"
echo "   - Press Cmd+Shift+P (Mac) or Ctrl+Shift+P (Windows/Linux)"
echo "   - Type 'Reload Window' and press Enter"
echo ""
echo "2️⃣  Update GitHub extensions:"
echo "   - Go to Extensions (Cmd+Shift+X or Ctrl+Shift+X)"
echo "   - Search for 'GitHub Copilot Chat' and update if available"
echo "   - Search for 'GitHub Pull Requests and Issues' and update if available"
echo ""
echo "3️⃣  If issues persist, disable and re-enable extensions:"
echo "   - Extensions → GitHub Copilot Chat → Disable"
echo "   - Restart VS Code"
echo "   - Extensions → GitHub Copilot Chat → Enable"
echo ""
echo "4️⃣  Clear VS Code cache (last resort):"
echo "   - Cmd+Shift+P → 'Developer: Reload Window'"
echo "   - Or restart VS Code completely"
echo ""

echo "✅ Your application is ready!"
echo "   - Stress Management Hub: Working ✓"
echo "   - Home Page: Working ✓"
echo "   - Development server: Runs on http://localhost:5174/"
echo ""

echo "🚀 To start development:"
echo "   cd frontend"
echo "   npm run dev"
echo ""
